export interface Book {
  id: string;
  title: string;
  author: string;
  coverImageUrl?: string;
  status: 'to-read' | 'reading' | 'finished';
  rating?: number; // Optional rating from 1-5
  notes?: string; // Optional review/notes
  createdAt: Date;
}

// A helper type for creating a new book, as the 'id' and 'createdAt'
// fields will be generated by the service/backend.
export type NewBook = Omit<Book, 'id' | 'createdAt'>;